export * from "./generated/api";
// Re-export TS interfaces, excluding SaveMapDataResponse which collides with the Zod schema
export type {
  AggregateStatsResponse,
  CompareResponse,
  CompareUserData,
  ConnectionOtherUser,
  ConnectionRecord,
  ConnectionRecordDirection,
  ConnectionRecordStatus,
  ConnectionsResponse,
  ConnectionsResponsePending,
  DeletePhotoResponse,
  DestinationRow,
  DestinationStatEntry,
  DestinationStatsResponse,
  ErrorEnvelope,
  GetAggregateStatsCategory,
  GetAggregateStatsParams,
  GetDestinationStatsParams,
  HealthStatus,
  LeaderboardEntry,
  LeaderboardResponse,
  LeaderboardVisitedCounts,
  ListPhotosParams,
  MapDataEnvelope,
  MapDataPayload,
  MapDataPayloadCountryDetails,
  MapDataPayloadNotesByKey,
  MapDataPayloadParkDetails,
  MapDataPayloadProvinceDetails,
  MapDataPayloadStadiumDetails,
  MapDataPayloadStateDetails,
  MapDataPayloadTccDetails,
  PhotoListResponse,
  PhotoRecord,
  SearchUsersParams,
  SetUsernameBody,
  SetUsernameResponse,
  UpdatePhotoBody,
  UploadPhotoBody,
  UserProfile,
} from "./generated/types";
