export interface RegionInfo {
  name: string;
  regionType: "country" | "us-state" | "ca-province";
  capital: string;
  population: string;
  area: string;
  currency?: string;
  language?: string;
  continent?: string;
  joined?: string;
  nickname?: string;
  flag?: string;
}

export type RegionRecord = Record<string, RegionInfo>;

export const COUNTRY_DATA: RegionRecord = {
  "004": { name: "Afghanistan", regionType: "country", capital: "Kabul", population: "40.1M", area: "652,864 km²", continent: "Asia", currency: "Afghan Afghani", language: "Dari, Pashto" },
  "008": { name: "Albania", regionType: "country", capital: "Tirana", population: "2.8M", area: "28,748 km²", continent: "Europe", currency: "Albanian Lek", language: "Albanian" },
  "012": { name: "Algeria", regionType: "country", capital: "Algiers", population: "44.6M", area: "2,381,741 km²", continent: "Africa", currency: "Algerian Dinar", language: "Arabic, Tamazight" },
  "024": { name: "Angola", regionType: "country", capital: "Luanda", population: "34.5M", area: "1,246,700 km²", continent: "Africa", currency: "Kwanza", language: "Portuguese" },
  "032": { name: "Argentina", regionType: "country", capital: "Buenos Aires", population: "45.8M", area: "2,780,400 km²", continent: "South America", currency: "Argentine Peso", language: "Spanish" },
  "036": { name: "Australia", regionType: "country", capital: "Canberra", population: "26.1M", area: "7,692,024 km²", continent: "Oceania", currency: "Australian Dollar", language: "English" },
  "040": { name: "Austria", regionType: "country", capital: "Vienna", population: "9.1M", area: "83,871 km²", continent: "Europe", currency: "Euro", language: "German" },
  "050": { name: "Bangladesh", regionType: "country", capital: "Dhaka", population: "168.1M", area: "147,570 km²", continent: "Asia", currency: "Bangladeshi Taka", language: "Bengali" },
  "056": { name: "Belgium", regionType: "country", capital: "Brussels", population: "11.6M", area: "30,528 km²", continent: "Europe", currency: "Euro", language: "Dutch, French, German" },
  "064": { name: "Bhutan", regionType: "country", capital: "Thimphu", population: "0.8M", area: "38,394 km²", continent: "Asia", currency: "Bhutanese Ngultrum", language: "Dzongkha" },
  "068": { name: "Bolivia", regionType: "country", capital: "Sucre", population: "12.1M", area: "1,098,581 km²", continent: "South America", currency: "Bolivian Boliviano", language: "Spanish" },
  "076": { name: "Brazil", regionType: "country", capital: "Brasília", population: "215.3M", area: "8,515,767 km²", continent: "South America", currency: "Brazilian Real", language: "Portuguese" },
  "100": { name: "Bulgaria", regionType: "country", capital: "Sofia", population: "6.5M", area: "110,879 km²", continent: "Europe", currency: "Bulgarian Lev", language: "Bulgarian" },
  "116": { name: "Cambodia", regionType: "country", capital: "Phnom Penh", population: "16.7M", area: "181,035 km²", continent: "Asia", currency: "Cambodian Riel", language: "Khmer" },
  "120": { name: "Cameroon", regionType: "country", capital: "Yaoundé", population: "27.2M", area: "475,442 km²", continent: "Africa", currency: "Central African CFA Franc", language: "French, English" },
  "152": { name: "Chile", regionType: "country", capital: "Santiago", population: "19.5M", area: "756,102 km²", continent: "South America", currency: "Chilean Peso", language: "Spanish" },
  "156": { name: "China", regionType: "country", capital: "Beijing", population: "1.4B", area: "9,596,960 km²", continent: "Asia", currency: "Chinese Yuan", language: "Mandarin Chinese" },
  "170": { name: "Colombia", regionType: "country", capital: "Bogotá", population: "51.9M", area: "1,141,748 km²", continent: "South America", currency: "Colombian Peso", language: "Spanish" },
  "178": { name: "Republic of the Congo", regionType: "country", capital: "Brazzaville", population: "5.8M", area: "342,000 km²", continent: "Africa", currency: "Central African CFA Franc", language: "French" },
  "180": { name: "DR Congo", regionType: "country", capital: "Kinshasa", population: "99.0M", area: "2,344,858 km²", continent: "Africa", currency: "Congolese Franc", language: "French" },
  "188": { name: "Costa Rica", regionType: "country", capital: "San José", population: "5.2M", area: "51,100 km²", continent: "North America", currency: "Costa Rican Colón", language: "Spanish" },
  "191": { name: "Croatia", regionType: "country", capital: "Zagreb", population: "3.9M", area: "56,594 km²", continent: "Europe", currency: "Euro", language: "Croatian" },
  "203": { name: "Czech Republic", regionType: "country", capital: "Prague", population: "10.9M", area: "78,866 km²", continent: "Europe", currency: "Czech Koruna", language: "Czech" },
  "208": { name: "Denmark", regionType: "country", capital: "Copenhagen", population: "5.9M", area: "43,094 km²", continent: "Europe", currency: "Danish Krone", language: "Danish" },
  "214": { name: "Dominican Republic", regionType: "country", capital: "Santo Domingo", population: "11.1M", area: "48,671 km²", continent: "North America", currency: "Dominican Peso", language: "Spanish" },
  "218": { name: "Ecuador", regionType: "country", capital: "Quito", population: "18.0M", area: "283,561 km²", continent: "South America", currency: "US Dollar", language: "Spanish" },
  "818": { name: "Egypt", regionType: "country", capital: "Cairo", population: "102.3M", area: "1,002,450 km²", continent: "Africa", currency: "Egyptian Pound", language: "Arabic" },
  "231": { name: "Ethiopia", regionType: "country", capital: "Addis Ababa", population: "120.8M", area: "1,104,300 km²", continent: "Africa", currency: "Ethiopian Birr", language: "Amharic" },
  "246": { name: "Finland", regionType: "country", capital: "Helsinki", population: "5.5M", area: "338,435 km²", continent: "Europe", currency: "Euro", language: "Finnish, Swedish" },
  "250": { name: "France", regionType: "country", capital: "Paris", population: "67.8M", area: "551,695 km²", continent: "Europe", currency: "Euro", language: "French" },
  "276": { name: "Germany", regionType: "country", capital: "Berlin", population: "83.8M", area: "357,114 km²", continent: "Europe", currency: "Euro", language: "German" },
  "288": { name: "Ghana", regionType: "country", capital: "Accra", population: "32.8M", area: "238,533 km²", continent: "Africa", currency: "Ghanaian Cedi", language: "English" },
  "300": { name: "Greece", regionType: "country", capital: "Athens", population: "10.4M", area: "131,957 km²", continent: "Europe", currency: "Euro", language: "Greek" },
  "304": { name: "Greenland", regionType: "country", capital: "Nuuk", population: "0.06M", area: "2,166,086 km²", continent: "North America", currency: "Danish Krone", language: "Greenlandic, Danish" },
  "320": { name: "Guatemala", regionType: "country", capital: "Guatemala City", population: "17.8M", area: "108,889 km²", continent: "North America", currency: "Guatemalan Quetzal", language: "Spanish" },
  "348": { name: "Hungary", regionType: "country", capital: "Budapest", population: "9.7M", area: "93,028 km²", continent: "Europe", currency: "Hungarian Forint", language: "Hungarian" },
  "356": { name: "India", regionType: "country", capital: "New Delhi", population: "1.4B", area: "3,287,263 km²", continent: "Asia", currency: "Indian Rupee", language: "Hindi, English" },
  "360": { name: "Indonesia", regionType: "country", capital: "Jakarta", population: "273.8M", area: "1,904,569 km²", continent: "Asia", currency: "Indonesian Rupiah", language: "Indonesian" },
  "364": { name: "Iran", regionType: "country", capital: "Tehran", population: "85.9M", area: "1,648,195 km²", continent: "Asia", currency: "Iranian Rial", language: "Persian" },
  "368": { name: "Iraq", regionType: "country", capital: "Baghdad", population: "42.2M", area: "438,317 km²", continent: "Asia", currency: "Iraqi Dinar", language: "Arabic, Kurdish" },
  "372": { name: "Ireland", regionType: "country", capital: "Dublin", population: "5.1M", area: "70,273 km²", continent: "Europe", currency: "Euro", language: "English, Irish" },
  "376": { name: "Israel", regionType: "country", capital: "Jerusalem", population: "9.5M", area: "20,770 km²", continent: "Asia", currency: "Israeli New Shekel", language: "Hebrew, Arabic" },
  "380": { name: "Italy", regionType: "country", capital: "Rome", population: "60.0M", area: "301,340 km²", continent: "Europe", currency: "Euro", language: "Italian" },
  "392": { name: "Japan", regionType: "country", capital: "Tokyo", population: "125.7M", area: "377,975 km²", continent: "Asia", currency: "Japanese Yen", language: "Japanese" },
  "400": { name: "Jordan", regionType: "country", capital: "Amman", population: "10.3M", area: "89,342 km²", continent: "Asia", currency: "Jordanian Dinar", language: "Arabic" },
  "398": { name: "Kazakhstan", regionType: "country", capital: "Astana", population: "19.2M", area: "2,724,900 km²", continent: "Asia", currency: "Kazakhstani Tenge", language: "Kazakh, Russian" },
  "404": { name: "Kenya", regionType: "country", capital: "Nairobi", population: "54.0M", area: "580,367 km²", continent: "Africa", currency: "Kenyan Shilling", language: "Swahili, English" },
  "408": { name: "North Korea", regionType: "country", capital: "Pyongyang", population: "25.9M", area: "120,538 km²", continent: "Asia", currency: "North Korean Won", language: "Korean" },
  "410": { name: "South Korea", regionType: "country", capital: "Seoul", population: "51.7M", area: "100,210 km²", continent: "Asia", currency: "South Korean Won", language: "Korean" },
  "418": { name: "Laos", regionType: "country", capital: "Vientiane", population: "7.4M", area: "236,800 km²", continent: "Asia", currency: "Lao Kip", language: "Lao" },
  "434": { name: "Libya", regionType: "country", capital: "Tripoli", population: "7.0M", area: "1,759,541 km²", continent: "Africa", currency: "Libyan Dinar", language: "Arabic" },
  "484": { name: "Mexico", regionType: "country", capital: "Mexico City", population: "130.3M", area: "1,964,375 km²", continent: "North America", currency: "Mexican Peso", language: "Spanish" },
  "496": { name: "Mongolia", regionType: "country", capital: "Ulaanbaatar", population: "3.4M", area: "1,564,116 km²", continent: "Asia", currency: "Mongolian Tögrög", language: "Mongolian" },
  "504": { name: "Morocco", regionType: "country", capital: "Rabat", population: "37.5M", area: "446,550 km²", continent: "Africa", currency: "Moroccan Dirham", language: "Arabic, Tamazight" },
  "508": { name: "Mozambique", regionType: "country", capital: "Maputo", population: "32.8M", area: "801,590 km²", continent: "Africa", currency: "Mozambican Metical", language: "Portuguese" },
  "524": { name: "Nepal", regionType: "country", capital: "Kathmandu", population: "29.7M", area: "147,181 km²", continent: "Asia", currency: "Nepalese Rupee", language: "Nepali" },
  "528": { name: "Netherlands", regionType: "country", capital: "Amsterdam", population: "17.7M", area: "41,543 km²", continent: "Europe", currency: "Euro", language: "Dutch" },
  "554": { name: "New Zealand", regionType: "country", capital: "Wellington", population: "5.1M", area: "270,467 km²", continent: "Oceania", currency: "New Zealand Dollar", language: "English, Māori" },
  "562": { name: "Niger", regionType: "country", capital: "Niamey", population: "25.2M", area: "1,267,000 km²", continent: "Africa", currency: "West African CFA Franc", language: "French" },
  "566": { name: "Nigeria", regionType: "country", capital: "Abuja", population: "218.5M", area: "923,768 km²", continent: "Africa", currency: "Nigerian Naira", language: "English" },
  "578": { name: "Norway", regionType: "country", capital: "Oslo", population: "5.4M", area: "385,207 km²", continent: "Europe", currency: "Norwegian Krone", language: "Norwegian" },
  "586": { name: "Pakistan", regionType: "country", capital: "Islamabad", population: "231.4M", area: "881,913 km²", continent: "Asia", currency: "Pakistani Rupee", language: "Urdu, English" },
  "600": { name: "Paraguay", regionType: "country", capital: "Asunción", population: "7.4M", area: "406,752 km²", continent: "South America", currency: "Paraguayan Guaraní", language: "Spanish, Guaraní" },
  "604": { name: "Peru", regionType: "country", capital: "Lima", population: "33.4M", area: "1,285,216 km²", continent: "South America", currency: "Peruvian Sol", language: "Spanish" },
  "608": { name: "Philippines", regionType: "country", capital: "Manila", population: "114.1M", area: "300,000 km²", continent: "Asia", currency: "Philippine Peso", language: "Filipino, English" },
  "616": { name: "Poland", regionType: "country", capital: "Warsaw", population: "37.8M", area: "312,696 km²", continent: "Europe", currency: "Polish Złoty", language: "Polish" },
  "620": { name: "Portugal", regionType: "country", capital: "Lisbon", population: "10.3M", area: "92,212 km²", continent: "Europe", currency: "Euro", language: "Portuguese" },
  "642": { name: "Romania", regionType: "country", capital: "Bucharest", population: "19.0M", area: "238,397 km²", continent: "Europe", currency: "Romanian Leu", language: "Romanian" },
  "643": { name: "Russia", regionType: "country", capital: "Moscow", population: "145.5M", area: "17,098,242 km²", continent: "Europe/Asia", currency: "Russian Ruble", language: "Russian" },
  "682": { name: "Saudi Arabia", regionType: "country", capital: "Riyadh", population: "35.6M", area: "2,149,690 km²", continent: "Asia", currency: "Saudi Riyal", language: "Arabic" },
  "686": { name: "Senegal", regionType: "country", capital: "Dakar", population: "17.8M", area: "196,722 km²", continent: "Africa", currency: "West African CFA Franc", language: "French" },
  "706": { name: "Somalia", regionType: "country", capital: "Mogadishu", population: "17.1M", area: "637,657 km²", continent: "Africa", currency: "Somali Shilling", language: "Somali, Arabic" },
  "710": { name: "South Africa", regionType: "country", capital: "Pretoria", population: "60.0M", area: "1,221,037 km²", continent: "Africa", currency: "South African Rand", language: "11 official languages" },
  "724": { name: "Spain", regionType: "country", capital: "Madrid", population: "47.4M", area: "505,990 km²", continent: "Europe", currency: "Euro", language: "Spanish" },
  "729": { name: "Sudan", regionType: "country", capital: "Khartoum", population: "44.9M", area: "1,861,484 km²", continent: "Africa", currency: "Sudanese Pound", language: "Arabic, English" },
  "752": { name: "Sweden", regionType: "country", capital: "Stockholm", population: "10.5M", area: "450,295 km²", continent: "Europe", currency: "Swedish Krona", language: "Swedish" },
  "756": { name: "Switzerland", regionType: "country", capital: "Bern", population: "8.7M", area: "41,285 km²", continent: "Europe", currency: "Swiss Franc", language: "German, French, Italian, Romansh" },
  "760": { name: "Syria", regionType: "country", capital: "Damascus", population: "21.3M", area: "185,180 km²", continent: "Asia", currency: "Syrian Pound", language: "Arabic" },
  "762": { name: "Tajikistan", regionType: "country", capital: "Dushanbe", population: "10.0M", area: "143,100 km²", continent: "Asia", currency: "Tajikistani Somoni", language: "Tajik" },
  "834": { name: "Tanzania", regionType: "country", capital: "Dodoma", population: "63.7M", area: "945,087 km²", continent: "Africa", currency: "Tanzanian Shilling", language: "Swahili, English" },
  "764": { name: "Thailand", regionType: "country", capital: "Bangkok", population: "71.6M", area: "513,120 km²", continent: "Asia", currency: "Thai Baht", language: "Thai" },
  "788": { name: "Tunisia", regionType: "country", capital: "Tunis", population: "12.1M", area: "163,610 km²", continent: "Africa", currency: "Tunisian Dinar", language: "Arabic" },
  "792": { name: "Turkey", regionType: "country", capital: "Ankara", population: "84.7M", area: "783,562 km²", continent: "Asia/Europe", currency: "Turkish Lira", language: "Turkish" },
  "800": { name: "Uganda", regionType: "country", capital: "Kampala", population: "47.1M", area: "241,550 km²", continent: "Africa", currency: "Ugandan Shilling", language: "English, Swahili" },
  "804": { name: "Ukraine", regionType: "country", capital: "Kyiv", population: "44.0M", area: "603,550 km²", continent: "Europe", currency: "Ukrainian Hryvnia", language: "Ukrainian" },
  "784": { name: "United Arab Emirates", regionType: "country", capital: "Abu Dhabi", population: "10.0M", area: "83,600 km²", continent: "Asia", currency: "UAE Dirham", language: "Arabic" },
  "826": { name: "United Kingdom", regionType: "country", capital: "London", population: "67.1M", area: "242,495 km²", continent: "Europe", currency: "British Pound", language: "English" },
  "858": { name: "Uruguay", regionType: "country", capital: "Montevideo", population: "3.5M", area: "176,215 km²", continent: "South America", currency: "Uruguayan Peso", language: "Spanish" },
  "860": { name: "Uzbekistan", regionType: "country", capital: "Tashkent", population: "35.3M", area: "448,978 km²", continent: "Asia", currency: "Uzbekistani Som", language: "Uzbek" },
  "862": { name: "Venezuela", regionType: "country", capital: "Caracas", population: "28.7M", area: "912,050 km²", continent: "South America", currency: "Venezuelan Bolívar", language: "Spanish" },
  "704": { name: "Vietnam", regionType: "country", capital: "Hanoi", population: "97.3M", area: "331,212 km²", continent: "Asia", currency: "Vietnamese Dong", language: "Vietnamese" },
  "887": { name: "Yemen", regionType: "country", capital: "Sana'a", population: "33.7M", area: "527,968 km²", continent: "Asia", currency: "Yemeni Rial", language: "Arabic" },
  "894": { name: "Zambia", regionType: "country", capital: "Lusaka", population: "19.5M", area: "752,618 km²", continent: "Africa", currency: "Zambian Kwacha", language: "Zambian Kwacha" },
  "716": { name: "Zimbabwe", regionType: "country", capital: "Harare", population: "15.1M", area: "390,757 km²", continent: "Africa", currency: "Zimbabwe Gold", language: "English and 15 others" },

  // Additional Africa
  "204": { name: "Benin", regionType: "country", capital: "Porto-Novo", population: "13.0M", area: "112,622 km²", continent: "Africa", currency: "West African CFA Franc", language: "French" },
  "854": { name: "Burkina Faso", regionType: "country", capital: "Ouagadougou", population: "22.1M", area: "274,222 km²", continent: "Africa", currency: "West African CFA Franc", language: "French" },
  "108": { name: "Burundi", regionType: "country", capital: "Gitega", population: "12.6M", area: "27,834 km²", continent: "Africa", currency: "Burundian Franc", language: "Kirundi, French" },
  "072": { name: "Botswana", regionType: "country", capital: "Gaborone", population: "2.6M", area: "581,730 km²", continent: "Africa", currency: "Botswana Pula", language: "Setswana, English" },
  "132": { name: "Cabo Verde", regionType: "country", capital: "Praia", population: "0.6M", area: "4,033 km²", continent: "Africa", currency: "Cape Verdean Escudo", language: "Portuguese" },
  "140": { name: "Central African Republic", regionType: "country", capital: "Bangui", population: "5.5M", area: "622,984 km²", continent: "Africa", currency: "Central African CFA Franc", language: "French, Sango" },
  "148": { name: "Chad", regionType: "country", capital: "N'Djamena", population: "17.4M", area: "1,284,000 km²", continent: "Africa", currency: "Central African CFA Franc", language: "French, Arabic" },
  "174": { name: "Comoros", regionType: "country", capital: "Moroni", population: "0.9M", area: "1,861 km²", continent: "Africa", currency: "Comorian Franc", language: "Comorian, Arabic, French" },
  "384": { name: "Côte d'Ivoire", regionType: "country", capital: "Yamoussoukro", population: "27.5M", area: "322,463 km²", continent: "Africa", currency: "West African CFA Franc", language: "French" },
  "262": { name: "Djibouti", regionType: "country", capital: "Djibouti City", population: "1.0M", area: "23,200 km²", continent: "Africa", currency: "Djiboutian Franc", language: "French, Arabic" },
  "226": { name: "Equatorial Guinea", regionType: "country", capital: "Malabo", population: "1.5M", area: "28,051 km²", continent: "Africa", currency: "Central African CFA Franc", language: "Spanish, French, Portuguese" },
  "232": { name: "Eritrea", regionType: "country", capital: "Asmara", population: "3.5M", area: "117,600 km²", continent: "Africa", currency: "Eritrean Nakfa", language: "Tigrinya, Arabic, English" },
  "748": { name: "Eswatini", regionType: "country", capital: "Mbabane", population: "1.2M", area: "17,364 km²", continent: "Africa", currency: "Swazi Lilangeni", language: "Swati, English" },
  "266": { name: "Gabon", regionType: "country", capital: "Libreville", population: "2.3M", area: "267,668 km²", continent: "Africa", currency: "Central African CFA Franc", language: "French" },
  "270": { name: "Gambia", regionType: "country", capital: "Banjul", population: "2.6M", area: "11,295 km²", continent: "Africa", currency: "Gambian Dalasi", language: "English" },
  "324": { name: "Guinea", regionType: "country", capital: "Conakry", population: "13.5M", area: "245,857 km²", continent: "Africa", currency: "Guinean Franc", language: "French" },
  "624": { name: "Guinea-Bissau", regionType: "country", capital: "Bissau", population: "2.1M", area: "36,125 km²", continent: "Africa", currency: "West African CFA Franc", language: "Portuguese" },
  "426": { name: "Lesotho", regionType: "country", capital: "Maseru", population: "2.3M", area: "30,355 km²", continent: "Africa", currency: "Lesotho Loti", language: "Sesotho, English" },
  "430": { name: "Liberia", regionType: "country", capital: "Monrovia", population: "5.3M", area: "111,369 km²", continent: "Africa", currency: "Liberian Dollar", language: "English" },
  "450": { name: "Madagascar", regionType: "country", capital: "Antananarivo", population: "28.9M", area: "587,041 km²", continent: "Africa", currency: "Malagasy Ariary", language: "Malagasy, French" },
  "454": { name: "Malawi", regionType: "country", capital: "Lilongwe", population: "20.4M", area: "118,484 km²", continent: "Africa", currency: "Malawian Kwacha", language: "Chichewa, English" },
  "466": { name: "Mali", regionType: "country", capital: "Bamako", population: "22.4M", area: "1,240,192 km²", continent: "Africa", currency: "West African CFA Franc", language: "French" },
  "478": { name: "Mauritania", regionType: "country", capital: "Nouakchott", population: "4.7M", area: "1,030,700 km²", continent: "Africa", currency: "Mauritanian Ouguiya", language: "Arabic" },
  "480": { name: "Mauritius", regionType: "country", capital: "Port Louis", population: "1.3M", area: "2,040 km²", continent: "Africa", currency: "Mauritian Rupee", language: "English, French, Creole" },
  "516": { name: "Namibia", regionType: "country", capital: "Windhoek", population: "2.6M", area: "824,292 km²", continent: "Africa", currency: "Namibian Dollar", language: "English" },
  "646": { name: "Rwanda", regionType: "country", capital: "Kigali", population: "13.8M", area: "26,338 km²", continent: "Africa", currency: "Rwandan Franc", language: "Kinyarwanda, French, English" },
  "678": { name: "São Tomé and Príncipe", regionType: "country", capital: "São Tomé", population: "0.2M", area: "964 km²", continent: "Africa", currency: "São Tomé dobra", language: "Portuguese" },
  "690": { name: "Seychelles", regionType: "country", capital: "Victoria", population: "0.1M", area: "459 km²", continent: "Africa", currency: "Seychellois Rupee", language: "Seychellois Creole, English, French" },
  "694": { name: "Sierra Leone", regionType: "country", capital: "Freetown", population: "8.4M", area: "71,740 km²", continent: "Africa", currency: "Sierra Leonean Leone", language: "English" },
  "728": { name: "South Sudan", regionType: "country", capital: "Juba", population: "11.0M", area: "619,745 km²", continent: "Africa", currency: "South Sudanese Pound", language: "English" },
  "768": { name: "Togo", regionType: "country", capital: "Lomé", population: "8.6M", area: "56,785 km²", continent: "Africa", currency: "West African CFA Franc", language: "French" },

  // Additional Asia
  "158": { name: "Taiwan", regionType: "country", capital: "Taipei", population: "23.6M", area: "36,193 km²", continent: "Asia", currency: "New Taiwan Dollar", language: "Mandarin Chinese" },
  "051": { name: "Armenia", regionType: "country", capital: "Yerevan", population: "2.9M", area: "29,743 km²", continent: "Asia", currency: "Armenian Dram", language: "Armenian" },
  "031": { name: "Azerbaijan", regionType: "country", capital: "Baku", population: "10.2M", area: "86,600 km²", continent: "Asia", currency: "Azerbaijani Manat", language: "Azerbaijani" },
  "048": { name: "Bahrain", regionType: "country", capital: "Manama", population: "1.5M", area: "765 km²", continent: "Asia", currency: "Bahraini Dinar", language: "Arabic" },
  "096": { name: "Brunei", regionType: "country", capital: "Bandar Seri Begawan", population: "0.4M", area: "5,765 km²", continent: "Asia", currency: "Brunei Dollar", language: "Malay, English" },
  "196": { name: "Cyprus", regionType: "country", capital: "Nicosia", population: "1.2M", area: "9,251 km²", continent: "Europe", currency: "Euro", language: "Greek, Turkish" },
  "268": { name: "Georgia", regionType: "country", capital: "Tbilisi", population: "3.7M", area: "69,700 km²", continent: "Asia", currency: "Georgian Lari", language: "Georgian" },
  "414": { name: "Kuwait", regionType: "country", capital: "Kuwait City", population: "4.3M", area: "17,818 km²", continent: "Asia", currency: "Kuwaiti Dinar", language: "Arabic" },
  "417": { name: "Kyrgyzstan", regionType: "country", capital: "Bishkek", population: "6.8M", area: "199,951 km²", continent: "Asia", currency: "Kyrgyzstani Som", language: "Kyrgyz, Russian" },
  "422": { name: "Lebanon", regionType: "country", capital: "Beirut", population: "5.5M", area: "10,452 km²", continent: "Asia", currency: "Lebanese Pound", language: "Arabic" },
  "458": { name: "Malaysia", regionType: "country", capital: "Kuala Lumpur", population: "33.6M", area: "329,847 km²", continent: "Asia", currency: "Malaysian Ringgit", language: "Malay" },
  "104": { name: "Myanmar", regionType: "country", capital: "Naypyidaw", population: "54.4M", area: "676,578 km²", continent: "Asia", currency: "Myanmar Kyat", language: "Burmese" },
  "512": { name: "Oman", regionType: "country", capital: "Muscat", population: "4.5M", area: "309,500 km²", continent: "Asia", currency: "Omani Rial", language: "Arabic" },
  "634": { name: "Qatar", regionType: "country", capital: "Doha", population: "2.9M", area: "11,586 km²", continent: "Asia", currency: "Qatari Riyal", language: "Arabic" },
  "702": { name: "Singapore", regionType: "country", capital: "Singapore", population: "5.9M", area: "719 km²", continent: "Asia", currency: "Singapore Dollar", language: "English, Malay, Mandarin, Tamil" },
  "144": { name: "Sri Lanka", regionType: "country", capital: "Sri Jayawardenepura Kotte", population: "22.2M", area: "65,610 km²", continent: "Asia", currency: "Sri Lankan Rupee", language: "Sinhala, Tamil" },
  "626": { name: "Timor-Leste", regionType: "country", capital: "Dili", population: "1.4M", area: "14,919 km²", continent: "Asia", currency: "US Dollar", language: "Tetum, Portuguese" },
  "795": { name: "Turkmenistan", regionType: "country", capital: "Ashgabat", population: "6.1M", area: "488,100 km²", continent: "Asia", currency: "Turkmenistani Manat", language: "Turkmen" },

  // Additional Europe
  "020": { name: "Andorra", regionType: "country", capital: "Andorra la Vella", population: "0.08M", area: "468 km²", continent: "Europe", currency: "Euro", language: "Catalan" },
  "112": { name: "Belarus", regionType: "country", capital: "Minsk", population: "9.4M", area: "207,600 km²", continent: "Europe", currency: "Belarusian Ruble", language: "Belarusian, Russian" },
  "070": { name: "Bosnia and Herzegovina", regionType: "country", capital: "Sarajevo", population: "3.2M", area: "51,209 km²", continent: "Europe", currency: "Bosnia-Herzegovina Convertible Mark", language: "Bosnian, Croatian, Serbian" },
  "233": { name: "Estonia", regionType: "country", capital: "Tallinn", population: "1.3M", area: "45,228 km²", continent: "Europe", currency: "Euro", language: "Estonian" },
  "352": { name: "Iceland", regionType: "country", capital: "Reykjavík", population: "0.4M", area: "103,000 km²", continent: "Europe", currency: "Icelandic Króna", language: "Icelandic" },
  "383": { name: "Kosovo", regionType: "country", capital: "Pristina", population: "1.8M", area: "10,908 km²", continent: "Europe", currency: "Euro", language: "Albanian, Serbian" },
  "428": { name: "Latvia", regionType: "country", capital: "Riga", population: "1.8M", area: "64,589 km²", continent: "Europe", currency: "Euro", language: "Latvian" },
  "438": { name: "Liechtenstein", regionType: "country", capital: "Vaduz", population: "0.04M", area: "160 km²", continent: "Europe", currency: "Swiss Franc", language: "German" },
  "440": { name: "Lithuania", regionType: "country", capital: "Vilnius", population: "2.8M", area: "65,300 km²", continent: "Europe", currency: "Euro", language: "Lithuanian" },
  "442": { name: "Luxembourg", regionType: "country", capital: "Luxembourg City", population: "0.7M", area: "2,586 km²", continent: "Europe", currency: "Euro", language: "Luxembourgish, French, German" },
  "470": { name: "Malta", regionType: "country", capital: "Valletta", population: "0.5M", area: "316 km²", continent: "Europe", currency: "Euro", language: "Maltese, English" },
  "498": { name: "Moldova", regionType: "country", capital: "Chișinău", population: "2.6M", area: "33,846 km²", continent: "Europe", currency: "Moldovan Leu", language: "Romanian" },
  "492": { name: "Monaco", regionType: "country", capital: "Monaco", population: "0.04M", area: "2 km²", continent: "Europe", currency: "Euro", language: "French" },
  "499": { name: "Montenegro", regionType: "country", capital: "Podgorica", population: "0.6M", area: "13,812 km²", continent: "Europe", currency: "Euro", language: "Montenegrin" },
  "807": { name: "North Macedonia", regionType: "country", capital: "Skopje", population: "2.1M", area: "25,713 km²", continent: "Europe", currency: "Macedonian Denar", language: "Macedonian" },
  "674": { name: "San Marino", regionType: "country", capital: "San Marino City", population: "0.03M", area: "61 km²", continent: "Europe", currency: "Euro", language: "Italian" },
  "336": { name: "Vatican City", regionType: "country", capital: "Vatican City", population: "0.0008M", area: "0.44 km²", continent: "Europe", currency: "Euro", language: "Italian, Latin" },
  "688": { name: "Serbia", regionType: "country", capital: "Belgrade", population: "6.8M", area: "77,474 km²", continent: "Europe", currency: "Serbian Dinar", language: "Serbian" },
  "703": { name: "Slovakia", regionType: "country", capital: "Bratislava", population: "5.5M", area: "49,035 km²", continent: "Europe", currency: "Euro", language: "Slovak" },
  "705": { name: "Slovenia", regionType: "country", capital: "Ljubljana", population: "2.1M", area: "20,273 km²", continent: "Europe", currency: "Euro", language: "Slovenian" },

  // Additional Americas
  "028": { name: "Antigua and Barbuda", regionType: "country", capital: "Saint John's", population: "0.1M", area: "443 km²", continent: "North America", currency: "East Caribbean Dollar", language: "English" },
  "044": { name: "Bahamas", regionType: "country", capital: "Nassau", population: "0.4M", area: "13,943 km²", continent: "North America", currency: "Bahamian Dollar", language: "English" },
  "052": { name: "Barbados", regionType: "country", capital: "Bridgetown", population: "0.3M", area: "430 km²", continent: "North America", currency: "Barbadian Dollar", language: "English" },
  "084": { name: "Belize", regionType: "country", capital: "Belmopan", population: "0.4M", area: "22,966 km²", continent: "North America", currency: "Belize Dollar", language: "English" },
  "192": { name: "Cuba", regionType: "country", capital: "Havana", population: "11.3M", area: "109,884 km²", continent: "North America", currency: "Cuban Peso", language: "Spanish" },
  "212": { name: "Dominica", regionType: "country", capital: "Roseau", population: "0.07M", area: "751 km²", continent: "North America", currency: "East Caribbean Dollar", language: "English" },
  "222": { name: "El Salvador", regionType: "country", capital: "San Salvador", population: "6.6M", area: "21,041 km²", continent: "North America", currency: "US Dollar", language: "Spanish" },
  "308": { name: "Grenada", regionType: "country", capital: "St. George's", population: "0.1M", area: "344 km²", continent: "North America", currency: "East Caribbean Dollar", language: "English" },
  "328": { name: "Guyana", regionType: "country", capital: "Georgetown", population: "0.8M", area: "214,969 km²", continent: "South America", currency: "Guyanese Dollar", language: "English" },
  "332": { name: "Haiti", regionType: "country", capital: "Port-au-Prince", population: "11.5M", area: "27,750 km²", continent: "North America", currency: "Haitian Gourde", language: "Haitian Creole, French" },
  "340": { name: "Honduras", regionType: "country", capital: "Tegucigalpa", population: "10.3M", area: "112,492 km²", continent: "North America", currency: "Honduran Lempira", language: "Spanish" },
  "388": { name: "Jamaica", regionType: "country", capital: "Kingston", population: "2.8M", area: "10,991 km²", continent: "North America", currency: "Jamaican Dollar", language: "English" },
  "558": { name: "Nicaragua", regionType: "country", capital: "Managua", population: "6.9M", area: "130,373 km²", continent: "North America", currency: "Nicaraguan Córdoba", language: "Spanish" },
  "591": { name: "Panama", regionType: "country", capital: "Panama City", population: "4.4M", area: "75,417 km²", continent: "North America", currency: "Panamanian Balboa", language: "Spanish" },
  "659": { name: "Saint Kitts and Nevis", regionType: "country", capital: "Basseterre", population: "0.05M", area: "261 km²", continent: "North America", currency: "East Caribbean Dollar", language: "English" },
  "662": { name: "Saint Lucia", regionType: "country", capital: "Castries", population: "0.18M", area: "616 km²", continent: "North America", currency: "East Caribbean Dollar", language: "English" },
  "670": { name: "Saint Vincent and the Grenadines", regionType: "country", capital: "Kingstown", population: "0.11M", area: "389 km²", continent: "North America", currency: "East Caribbean Dollar", language: "English" },
  "740": { name: "Suriname", regionType: "country", capital: "Paramaribo", population: "0.6M", area: "163,820 km²", continent: "South America", currency: "Surinamese Dollar", language: "Dutch" },
  "780": { name: "Trinidad and Tobago", regionType: "country", capital: "Port of Spain", population: "1.5M", area: "5,131 km²", continent: "North America", currency: "Trinidad and Tobago Dollar", language: "English" },

  // Additional Oceania
  "242": { name: "Fiji", regionType: "country", capital: "Suva", population: "0.9M", area: "18,272 km²", continent: "Oceania", currency: "Fijian Dollar", language: "English, Fijian, Hindi" },
  "296": { name: "Kiribati", regionType: "country", capital: "South Tarawa", population: "0.12M", area: "811 km²", continent: "Oceania", currency: "Australian Dollar", language: "English, Gilbertese" },
  "584": { name: "Marshall Islands", regionType: "country", capital: "Majuro", population: "0.04M", area: "181 km²", continent: "Oceania", currency: "US Dollar", language: "Marshallese, English" },
  "583": { name: "Micronesia", regionType: "country", capital: "Palikir", population: "0.1M", area: "702 km²", continent: "Oceania", currency: "US Dollar", language: "English" },
  "520": { name: "Nauru", regionType: "country", capital: "Yaren", population: "0.01M", area: "21 km²", continent: "Oceania", currency: "Australian Dollar", language: "Nauruan, English" },
  "585": { name: "Palau", regionType: "country", capital: "Ngerulmud", population: "0.02M", area: "459 km²", continent: "Oceania", currency: "US Dollar", language: "Palauan, English" },
  "598": { name: "Papua New Guinea", regionType: "country", capital: "Port Moresby", population: "10.3M", area: "462,840 km²", continent: "Oceania", currency: "Papua New Guinean Kina", language: "Tok Pisin, English, Hiri Motu" },
  "882": { name: "Samoa", regionType: "country", capital: "Apia", population: "0.2M", area: "2,842 km²", continent: "Oceania", currency: "Samoan Tālā", language: "Samoan, English" },
  "090": { name: "Solomon Islands", regionType: "country", capital: "Honiara", population: "0.7M", area: "28,896 km²", continent: "Oceania", currency: "Solomon Islands Dollar", language: "English" },
  "776": { name: "Tonga", regionType: "country", capital: "Nukuʻalofa", population: "0.1M", area: "747 km²", continent: "Oceania", currency: "Tongan Paʻanga", language: "Tongan, English" },
  "798": { name: "Tuvalu", regionType: "country", capital: "Funafuti", population: "0.01M", area: "26 km²", continent: "Oceania", currency: "Australian Dollar", language: "Tuvaluan, English" },
  "548": { name: "Vanuatu", regionType: "country", capital: "Port Vila", population: "0.3M", area: "12,189 km²", continent: "Oceania", currency: "Vanuatu Vatu", language: "Bislama, English, French" },

  "462": { name: "Maldives", regionType: "country", capital: "Malé", population: "0.5M", area: "298 km²", continent: "Asia", currency: "Maldivian Rufiyaa", language: "Dhivehi" },
  "275": { name: "Palestine", regionType: "country", capital: "Ramallah", population: "5.4M", area: "6,020 km²", continent: "Asia", currency: "Israeli New Shekel", language: "Arabic" },
};

export const US_STATE_DATA: RegionRecord = {
  "01": { name: "Alabama", regionType: "us-state", capital: "Montgomery", population: "5.1M", area: "135,767 km²", joined: "1819", nickname: "The Yellowhammer State" },
  "02": { name: "Alaska", regionType: "us-state", capital: "Juneau", population: "0.7M", area: "1,723,337 km²", joined: "1959", nickname: "The Last Frontier" },
  "04": { name: "Arizona", regionType: "us-state", capital: "Phoenix", population: "7.4M", area: "295,234 km²", joined: "1912", nickname: "The Grand Canyon State" },
  "05": { name: "Arkansas", regionType: "us-state", capital: "Little Rock", population: "3.0M", area: "137,732 km²", joined: "1836", nickname: "The Natural State" },
  "06": { name: "California", regionType: "us-state", capital: "Sacramento", population: "39.0M", area: "423,970 km²", joined: "1850", nickname: "The Golden State" },
  "08": { name: "Colorado", regionType: "us-state", capital: "Denver", population: "5.8M", area: "269,601 km²", joined: "1876", nickname: "The Centennial State" },
  "09": { name: "Connecticut", regionType: "us-state", capital: "Hartford", population: "3.6M", area: "14,357 km²", joined: "1788", nickname: "The Constitution State" },
  "10": { name: "Delaware", regionType: "us-state", capital: "Dover", population: "1.0M", area: "6,446 km²", joined: "1787", nickname: "The First State" },
  "11": { name: "District of Columbia", regionType: "us-state", capital: "Washington D.C.", population: "0.7M", area: "177 km²", joined: "1791", nickname: "The Nation's Capital" },
  "12": { name: "Florida", regionType: "us-state", capital: "Tallahassee", population: "22.6M", area: "170,312 km²", joined: "1845", nickname: "The Sunshine State" },
  "13": { name: "Georgia", regionType: "us-state", capital: "Atlanta", population: "10.9M", area: "153,910 km²", joined: "1788", nickname: "The Peach State" },
  "15": { name: "Hawaii", regionType: "us-state", capital: "Honolulu", population: "1.4M", area: "28,313 km²", joined: "1959", nickname: "The Aloha State" },
  "16": { name: "Idaho", regionType: "us-state", capital: "Boise", population: "1.9M", area: "216,443 km²", joined: "1890", nickname: "The Gem State" },
  "17": { name: "Illinois", regionType: "us-state", capital: "Springfield", population: "12.6M", area: "149,995 km²", joined: "1818", nickname: "The Prairie State" },
  "18": { name: "Indiana", regionType: "us-state", capital: "Indianapolis", population: "6.8M", area: "94,326 km²", joined: "1816", nickname: "The Hoosier State" },
  "19": { name: "Iowa", regionType: "us-state", capital: "Des Moines", population: "3.2M", area: "145,746 km²", joined: "1846", nickname: "The Hawkeye State" },
  "20": { name: "Kansas", regionType: "us-state", capital: "Topeka", population: "2.9M", area: "213,100 km²", joined: "1861", nickname: "The Sunflower State" },
  "21": { name: "Kentucky", regionType: "us-state", capital: "Frankfort", population: "4.5M", area: "104,656 km²", joined: "1792", nickname: "The Bluegrass State" },
  "22": { name: "Louisiana", regionType: "us-state", capital: "Baton Rouge", population: "4.6M", area: "135,659 km²", joined: "1812", nickname: "The Pelican State" },
  "23": { name: "Maine", regionType: "us-state", capital: "Augusta", population: "1.4M", area: "91,633 km²", joined: "1820", nickname: "The Pine Tree State" },
  "24": { name: "Maryland", regionType: "us-state", capital: "Annapolis", population: "6.2M", area: "32,133 km²", joined: "1788", nickname: "The Old Line State" },
  "25": { name: "Massachusetts", regionType: "us-state", capital: "Boston", population: "7.0M", area: "27,336 km²", joined: "1788", nickname: "The Bay State" },
  "26": { name: "Michigan", regionType: "us-state", capital: "Lansing", population: "10.0M", area: "250,487 km²", joined: "1837", nickname: "The Great Lakes State" },
  "27": { name: "Minnesota", regionType: "us-state", capital: "Saint Paul", population: "5.7M", area: "225,163 km²", joined: "1858", nickname: "The North Star State" },
  "28": { name: "Mississippi", regionType: "us-state", capital: "Jackson", population: "2.9M", area: "125,438 km²", joined: "1817", nickname: "The Magnolia State" },
  "29": { name: "Missouri", regionType: "us-state", capital: "Jefferson City", population: "6.2M", area: "180,540 km²", joined: "1821", nickname: "The Show-Me State" },
  "30": { name: "Montana", regionType: "us-state", capital: "Helena", population: "1.1M", area: "380,831 km²", joined: "1889", nickname: "Big Sky Country" },
  "31": { name: "Nebraska", regionType: "us-state", capital: "Lincoln", population: "1.9M", area: "200,330 km²", joined: "1867", nickname: "The Cornhusker State" },
  "32": { name: "Nevada", regionType: "us-state", capital: "Carson City", population: "3.1M", area: "286,352 km²", joined: "1864", nickname: "The Silver State" },
  "33": { name: "New Hampshire", regionType: "us-state", capital: "Concord", population: "1.4M", area: "24,214 km²", joined: "1788", nickname: "The Granite State" },
  "34": { name: "New Jersey", regionType: "us-state", capital: "Trenton", population: "9.3M", area: "22,591 km²", joined: "1787", nickname: "The Garden State" },
  "35": { name: "New Mexico", regionType: "us-state", capital: "Santa Fe", population: "2.1M", area: "314,917 km²", joined: "1912", nickname: "Land of Enchantment" },
  "36": { name: "New York", regionType: "us-state", capital: "Albany", population: "20.2M", area: "141,297 km²", joined: "1788", nickname: "The Empire State" },
  "37": { name: "North Carolina", regionType: "us-state", capital: "Raleigh", population: "10.7M", area: "139,391 km²", joined: "1789", nickname: "The Tar Heel State" },
  "38": { name: "North Dakota", regionType: "us-state", capital: "Bismarck", population: "0.8M", area: "183,108 km²", joined: "1889", nickname: "The Peace Garden State" },
  "39": { name: "Ohio", regionType: "us-state", capital: "Columbus", population: "11.8M", area: "116,098 km²", joined: "1803", nickname: "The Buckeye State" },
  "40": { name: "Oklahoma", regionType: "us-state", capital: "Oklahoma City", population: "4.0M", area: "181,037 km²", joined: "1907", nickname: "The Sooner State" },
  "41": { name: "Oregon", regionType: "us-state", capital: "Salem", population: "4.2M", area: "254,800 km²", joined: "1859", nickname: "The Beaver State" },
  "42": { name: "Pennsylvania", regionType: "us-state", capital: "Harrisburg", population: "13.0M", area: "119,279 km²", joined: "1787", nickname: "The Keystone State" },
  "44": { name: "Rhode Island", regionType: "us-state", capital: "Providence", population: "1.1M", area: "4,001 km²", joined: "1790", nickname: "The Ocean State" },
  "45": { name: "South Carolina", regionType: "us-state", capital: "Columbia", population: "5.3M", area: "82,933 km²", joined: "1788", nickname: "The Palmetto State" },
  "46": { name: "South Dakota", regionType: "us-state", capital: "Pierre", population: "0.9M", area: "199,729 km²", joined: "1889", nickname: "The Mount Rushmore State" },
  "47": { name: "Tennessee", regionType: "us-state", capital: "Nashville", population: "7.0M", area: "109,153 km²", joined: "1796", nickname: "The Volunteer State" },
  "48": { name: "Texas", regionType: "us-state", capital: "Austin", population: "30.0M", area: "695,662 km²", joined: "1845", nickname: "The Lone Star State" },
  "49": { name: "Utah", regionType: "us-state", capital: "Salt Lake City", population: "3.4M", area: "219,882 km²", joined: "1896", nickname: "The Beehive State" },
  "50": { name: "Vermont", regionType: "us-state", capital: "Montpelier", population: "0.6M", area: "24,906 km²", joined: "1791", nickname: "The Green Mountain State" },
  "51": { name: "Virginia", regionType: "us-state", capital: "Richmond", population: "8.7M", area: "110,787 km²", joined: "1788", nickname: "The Old Dominion" },
  "53": { name: "Washington", regionType: "us-state", capital: "Olympia", population: "7.8M", area: "184,661 km²", joined: "1889", nickname: "The Evergreen State" },
  "54": { name: "West Virginia", regionType: "us-state", capital: "Charleston", population: "1.8M", area: "62,756 km²", joined: "1863", nickname: "The Mountain State" },
  "55": { name: "Wisconsin", regionType: "us-state", capital: "Madison", population: "5.9M", area: "169,635 km²", joined: "1848", nickname: "The Badger State" },
  "56": { name: "Wyoming", regionType: "us-state", capital: "Cheyenne", population: "0.6M", area: "253,335 km²", joined: "1890", nickname: "The Equality State" },
};

export const CA_PROVINCE_DATA: Record<string, RegionInfo> = {
  "Alberta": { name: "Alberta", regionType: "ca-province", capital: "Edmonton", population: "4.6M", area: "661,848 km²", joined: "1905", nickname: "Wild Rose Country" },
  "British Columbia": { name: "British Columbia", regionType: "ca-province", capital: "Victoria", population: "5.4M", area: "944,735 km²", joined: "1871", nickname: "Beautiful British Columbia" },
  "Manitoba": { name: "Manitoba", regionType: "ca-province", capital: "Winnipeg", population: "1.4M", area: "647,797 km²", joined: "1870", nickname: "The Keystone Province" },
  "New Brunswick": { name: "New Brunswick", regionType: "ca-province", capital: "Fredericton", population: "0.8M", area: "72,908 km²", joined: "1867", nickname: "The Picture Province" },
  "Newfoundland and Labrador": { name: "Newfoundland and Labrador", regionType: "ca-province", capital: "St. John's", population: "0.5M", area: "405,212 km²", joined: "1949", nickname: "The Rock" },
  "Northwest Territories": { name: "Northwest Territories", regionType: "ca-province", capital: "Yellowknife", population: "0.045M", area: "1,346,106 km²", joined: "1870", nickname: "Spectacular NWT" },
  "Nova Scotia": { name: "Nova Scotia", regionType: "ca-province", capital: "Halifax", population: "1.0M", area: "55,284 km²", joined: "1867", nickname: "Canada's Ocean Playground" },
  "Nunavut": { name: "Nunavut", regionType: "ca-province", capital: "Iqaluit", population: "0.04M", area: "2,093,190 km²", joined: "1999", nickname: "Our Land" },
  "Ontario": { name: "Ontario", regionType: "ca-province", capital: "Toronto", population: "14.9M", area: "1,076,395 km²", joined: "1867", nickname: "Yours to Discover" },
  "Prince Edward Island": { name: "Prince Edward Island", regionType: "ca-province", capital: "Charlottetown", population: "0.17M", area: "5,660 km²", joined: "1873", nickname: "The Garden Province" },
  "Quebec": { name: "Quebec", regionType: "ca-province", capital: "Quebec City", population: "8.8M", area: "1,542,056 km²", joined: "1867", nickname: "La Belle Province" },
  "Saskatchewan": { name: "Saskatchewan", regionType: "ca-province", capital: "Regina", population: "1.2M", area: "651,036 km²", joined: "1905", nickname: "The Land of Living Skies" },
  "Yukon Territory": { name: "Yukon Territory", regionType: "ca-province", capital: "Whitehorse", population: "0.04M", area: "482,443 km²", joined: "1898", nickname: "Canada's True North" },
};

export const CONTINENT_COLORS: Record<string, string> = {
  "Africa": "#f59e0b",
  "Asia": "#10b981",
  "Europe": "#3b82f6",
  "North America": "#ef4444",
  "South America": "#8b5cf6",
  "Oceania": "#06b6d4",
  "Asia/Europe": "#6366f1",
  "Europe/Asia": "#6366f1",
};
