// Travelers' Century Club — official list of 330 countries and territories
// (as of January 2022). Source: travelerscenturyclub.org

export type TccRegionKey =
  | "PAC" | "NA" | "CAM" | "SAM" | "CAR" | "ATL"
  | "EUR" | "ANT" | "AFR" | "ME"  | "IND" | "ASI";

export interface TccRegion {
  name: string;
  color: string;
  fillUnvisited: string;
}

export const TCC_REGIONS: Record<TccRegionKey, TccRegion> = {
  PAC: { name: "Pacific Ocean",         color: "#06b6d4", fillUnvisited: "#164e5b" },
  NA:  { name: "North America",         color: "#ef4444", fillUnvisited: "#5a1f1f" },
  CAM: { name: "Central America",       color: "#f97316", fillUnvisited: "#5a2e10" },
  SAM: { name: "South America",         color: "#a855f7", fillUnvisited: "#3e1f5a" },
  CAR: { name: "Caribbean",             color: "#ec4899", fillUnvisited: "#5a1e3a" },
  ATL: { name: "Atlantic Ocean",        color: "#3b82f6", fillUnvisited: "#1f3658" },
  EUR: { name: "Europe & Mediterranean", color: "#10b981", fillUnvisited: "#0e3f33" },
  ANT: { name: "Antarctica",            color: "#cbd5e1", fillUnvisited: "#3a4555" },
  AFR: { name: "Africa",                color: "#f59e0b", fillUnvisited: "#523619" },
  ME:  { name: "Middle East",           color: "#f43f5e", fillUnvisited: "#591c2c" },
  IND: { name: "Indian Ocean",          color: "#0ea5e9", fillUnvisited: "#16415a" },
  ASI: { name: "Asia",                  color: "#84cc16", fillUnvisited: "#324c14" },
};

export interface TccEntry {
  name: string;        // canonical TCC name (used as ID and storage key)
  region: TccRegionKey;
  geoId?: string;      // ISO 3166-1 numeric — entry "owns" this country shape on the map
  lng?: number;        // marker coordinates if no geoId
  lat?: number;
}

// Helper to keep the table compact and readable.
const e = (name: string, region: TccRegionKey, geoId?: string, lng?: number, lat?: number): TccEntry => {
  const out: TccEntry = { name, region };
  if (geoId !== undefined) out.geoId = geoId;
  if (lng !== undefined && lat !== undefined) { out.lng = lng; out.lat = lat; }
  return out;
};

export const TCC_DATA: TccEntry[] = [
  // A
  e("Abkhazia",                    "ASI", undefined, 40.99,  43.00),
  e("Abu Dhabi",                   "ME",  undefined, 54.37,  24.45),
  e("Afghanistan",                 "ASI", "004"),
  e("Ajman",                       "ME",  undefined, 55.55,  25.41),
  e("Aland Islands",               "EUR", undefined, 19.94,  60.18),
  e("Alaska",                      "NA",  undefined, -149.50, 64.20),
  e("Albania",                     "EUR", "008"),
  e("Algeria",                     "AFR", "012"),
  e("Andaman-Nicobar Islands",     "IND", undefined, 92.74,  11.74),
  e("Andorra",                     "EUR", "020"),
  e("Angola",                      "AFR", "024"),
  e("Anguilla",                    "CAR", undefined, -63.07, 18.22),
  e("Antigua & Barbuda",           "CAR", "028"),
  e("Argentina",                   "SAM", "032"),
  e("Argentine Antarctica",        "ANT", undefined, -65.00, -77.00),
  e("Armenia",                     "ASI", "051"),
  e("Aruba",                       "CAR", undefined, -69.97, 12.52),
  e("Ascension",                   "ATL", undefined, -14.37, -7.95),
  e("Austral Islands",             "PAC", undefined, -149.50, -23.40),
  e("Australia",                   "PAC", "036"),
  e("Australian Antarctic Territory","ANT", undefined, 105.00, -75.00),
  e("Austria",                     "EUR", "040"),
  e("Azerbaijan",                  "ASI", "031"),
  e("Azores Islands",              "ATL", undefined, -25.66, 37.74),
  // B
  e("Bahamas",                     "CAR", "044"),
  e("Bahrain",                     "ME",  "048"),
  e("Balearic Islands",            "EUR", undefined, 2.65,   39.57),
  e("Bangladesh",                  "ASI", "050"),
  e("Barbados",                    "CAR", "052"),
  e("Belarus",                     "EUR", "112"),
  e("Belgium",                     "EUR", "056"),
  e("Belize",                      "CAM", "084"),
  e("Benin",                       "AFR", "204"),
  e("Bermuda",                     "ATL", undefined, -64.78, 32.31),
  e("Bhutan",                      "ASI", "064"),
  e("Bismarck Archipelago",        "PAC", undefined, 152.47, -4.20),
  e("Bolivia",                     "SAM", "068"),
  e("Bonaire",                     "CAR", undefined, -68.27, 12.20),
  e("Bosnia & Herzegovina",        "EUR", "070"),
  e("Botswana",                    "AFR", "072"),
  e("Brazil",                      "SAM", "076"),
  e("British Antarctic Territory", "ANT", undefined, -58.00, -75.00),
  e("British Indian Ocean Territory","IND", undefined, 72.41, -7.31),
  e("Brunei",                      "ASI", "096"),
  e("Bulgaria",                    "EUR", "100"),
  e("Burkina Faso",                "AFR", "854"),
  e("Burundi",                     "AFR", "108"),
  // C
  e("Cabinda",                     "AFR", undefined, 12.20, -5.55),
  e("Cambodia",                    "ASI", "116"),
  e("Cameroon",                    "AFR", "120"),
  e("Canada",                      "NA",  "124"),
  e("Canary Islands",              "ATL", undefined, -15.43, 28.27),
  e("Cape Verde Islands",          "ATL", "132"),
  e("Cayman Islands",              "CAR", undefined, -81.27, 19.32),
  e("Central African Republic",    "AFR", "140"),
  e("Chad",                        "AFR", "148"),
  e("Chatham Islands",             "PAC", undefined, -176.50, -43.95),
  e("Chile",                       "SAM", "152"),
  e("Chilean Antarctic Territory", "ANT", undefined, -70.00, -80.00),
  e("China, People's Republic of", "ASI", "156"),
  e("Christmas Island",            "IND", undefined, 105.69, -10.45),
  e("Cocos (Keeling) Islands",     "IND", undefined, 96.84, -12.18),
  e("Colombia",                    "SAM", "170"),
  e("Comoros",                     "IND", "174"),
  e("Congo, Democratic Republic of (Kinshasa)","AFR", "180"),
  e("Congo, Republic of (Brazzaville)",        "AFR", "178"),
  e("Cook Islands",                "PAC", undefined, -159.78, -21.24),
  e("Corsica",                     "EUR", undefined, 9.10,  42.04),
  e("Costa Rica",                  "CAM", "188"),
  e("Côte d'Ivoire",               "AFR", "384"),
  e("Crete",                       "EUR", undefined, 24.81, 35.24),
  e("Croatia",                     "EUR", "191"),
  e("Cuba",                        "CAR", "192"),
  e("Curacao",                     "CAR", undefined, -69.04, 12.18),
  e("Cyprus, British Sovereign Base Areas","EUR", undefined, 33.40, 34.69),
  e("Cyprus, Republic of",         "EUR", "196"),
  e("Cyprus, Turkish Federated State of","EUR", undefined, 33.32, 35.18),
  e("Czech Republic",              "EUR", "203"),
  // D
  e("Denmark",                     "EUR", "208"),
  e("Djibouti",                    "AFR", "262"),
  e("Dominica",                    "CAR", "212"),
  e("Dominican Republic",          "CAR", "214"),
  e("Dubai",                       "ME",  undefined, 55.30, 25.27),
  // E
  e("Easter Island",               "PAC", undefined, -109.37, -27.12),
  e("Ecuador",                     "SAM", "218"),
  e("Egypt in Africa",             "AFR", undefined, 31.23, 30.04),
  e("Egypt in Asia (Sinai Peninsula)","ME", undefined, 33.83, 30.00),
  e("El Salvador",                 "CAM", "222"),
  e("England",                     "EUR", undefined, -0.13, 52.36),
  e("Equatorial Guinea (Bioko)",   "AFR", undefined, 8.78,  3.75),
  e("Equatorial Guinea (Rio Muni, Bata)","AFR", undefined, 10.27, 1.83),
  e("Eritrea",                     "AFR", "232"),
  e("Estonia",                     "EUR", "233"),
  e("Ethiopia",                    "AFR", "231"),
  // F
  e("Falkland Islands",            "ATL", undefined, -58.45, -51.74),
  e("Faroe Islands",               "ATL", undefined, -6.91, 62.00),
  e("Fernando de Noronha",         "ATL", undefined, -32.42, -3.85),
  e("Fiji Islands",                "PAC", "242"),
  e("Finland",                     "EUR", "246"),
  e("France",                      "EUR", "250"),
  e("French Antarctica",           "ANT", undefined, 70.00, -50.00),
  e("French Guiana",               "SAM", undefined, -53.00, 3.93),
  e("French Polynesia",            "PAC", undefined, -149.40, -17.70),
  e("Fujairah",                    "ME",  undefined, 56.34, 25.13),
  // G
  e("Gabon",                       "AFR", "266"),
  e("Galapagos Islands",           "PAC", undefined, -90.93, -0.95),
  e("Gambia",                      "AFR", "270"),
  e("Georgia",                     "ASI", "268"),
  e("Germany",                     "EUR", "276"),
  e("Ghana",                       "AFR", "288"),
  e("Gibraltar",                   "EUR", undefined, -5.35, 36.14),
  e("Greece",                      "EUR", "300"),
  e("Greek Aegean Islands",        "EUR", undefined, 25.45, 36.85),
  e("Greenland",                   "ATL", "304"),
  e("Grenada & Dependencies",      "CAR", "308"),
  e("Guadeloupe & Dependencies",   "CAR", undefined, -61.55, 16.27),
  e("Guam",                        "PAC", undefined, 144.79, 13.44),
  e("Guatemala",                   "CAM", "320"),
  e("Guernsey & Dependencies",     "EUR", undefined, -2.59, 49.46),
  e("Guinea",                      "AFR", "324"),
  e("Guinea-Bissau",               "AFR", "624"),
  e("Guyana",                      "SAM", "328"),
  // H
  e("Hainan Island",               "ASI", undefined, 109.84, 19.20),
  e("Haiti",                       "CAR", "332"),
  e("Hawaiian Islands",            "PAC", undefined, -155.58, 19.90),
  e("Honduras",                    "CAM", "340"),
  e("Hong Kong",                   "ASI", undefined, 114.17, 22.32),
  e("Hungary",                     "EUR", "348"),
  // I
  e("Iceland",                     "ATL", "352"),
  e("India",                       "ASI", "356"),
  e("Indonesia (Java)",            "ASI", "360"),
  e("Ionian Islands",              "EUR", undefined, 20.25, 38.75),
  e("Iran",                        "ME",  "364"),
  e("Iraq",                        "ME",  "368"),
  e("Ireland (Eire)",              "EUR", "372"),
  e("Ireland, Northern",           "EUR", undefined, -5.93, 54.60),
  e("Isle of Man",                 "EUR", undefined, -4.55, 54.24),
  e("Israel",                      "ME",  "376"),
  e("Italy",                       "EUR", "380"),
  // J
  e("Jamaica",                     "CAR", "388"),
  e("Japan",                       "ASI", "392"),
  e("Jeju Island",                 "ASI", undefined, 126.55, 33.49),
  e("Jersey",                      "EUR", undefined, -2.13, 49.21),
  e("Jordan",                      "ME",  "400"),
  e("Juan Fernandez Islands",      "PAC", undefined, -78.85, -33.62),
  // K
  e("Kalimantan",                  "ASI", undefined, 113.92, 0.79),
  e("Kaliningrad",                 "EUR", undefined, 20.51, 54.71),
  e("Kashmir",                     "ASI", undefined, 76.50, 34.10),
  e("Kazakhstan",                  "ASI", "398"),
  e("Kenya",                       "AFR", "404"),
  e("Kiribati",                    "PAC", "296"),
  e("Korea, North",                "ASI", "408"),
  e("Korea, South",                "ASI", "410"),
  e("Kosovo",                      "EUR", undefined, 21.00, 42.60),
  e("Kuwait",                      "ME",  "414"),
  e("Kyrgyzstan",                  "ASI", "417"),
  // L
  e("Lakshadweep",                 "IND", undefined, 73.04, 10.57),
  e("Lampedusa",                   "EUR", undefined, 12.61, 35.51),
  e("Laos",                        "ASI", "418"),
  e("Latvia",                      "EUR", "428"),
  e("Lebanon",                     "ME",  "422"),
  e("Lesotho",                     "AFR", "426"),
  e("Lesser Sunda Islands",        "ASI", undefined, 115.19, -8.65),
  e("Liberia",                     "AFR", "430"),
  e("Libya",                       "AFR", "434"),
  e("Liechtenstein",               "EUR", "438"),
  e("Line/Phoenix Islands",        "PAC", undefined, -157.36, 1.87),
  e("Lithuania",                   "EUR", "440"),
  e("Lord Howe Island",            "PAC", undefined, 159.08, -31.55),
  e("Luxembourg",                  "EUR", "442"),
  // M
  e("Macau",                       "ASI", undefined, 113.55, 22.20),
  e("Madagascar",                  "IND", "450"),
  e("Madeira",                     "ATL", undefined, -16.92, 32.76),
  e("Malawi",                      "AFR", "454"),
  e("Malaysia",                    "ASI", "458"),
  e("Maldives",                    "IND", "462"),
  e("Mali",                        "AFR", "466"),
  e("Malta",                       "EUR", "470"),
  e("Maluku Islands",              "ASI", undefined, 128.00, -3.00),
  e("Marquesas Islands",           "PAC", undefined, -139.00, -9.00),
  e("Marshall Islands, Republic of","PAC", "584"),
  e("Martinique",                  "CAR", undefined, -61.02, 14.64),
  e("Mauritania",                  "AFR", "478"),
  e("Mauritius & Dependencies",    "IND", "480"),
  e("Mayotte",                     "IND", undefined, 45.16, -12.83),
  e("Mexico",                      "NA",  "484"),
  e("Micronesia, Federated States of","PAC", "583"),
  e("Midway Island",               "PAC", undefined, -177.37, 28.21),
  e("Moldova",                     "EUR", "498"),
  e("Monaco",                      "EUR", "492"),
  e("Mongolia",                    "ASI", "496"),
  e("Montenegro",                  "EUR", "499"),
  e("Montserrat",                  "CAR", undefined, -62.21, 16.74),
  e("Morocco",                     "AFR", "504"),
  e("Morocco, Spanish (Ceuta, Melilla)","AFR", undefined, -5.34, 35.89),
  e("Mozambique",                  "AFR", "508"),
  e("Myanmar (Burma)",             "ASI", "104"),
  // N
  e("Nakhchivan",                  "ASI", undefined, 45.41, 39.21),
  e("Namibia",                     "AFR", "516"),
  e("Nauru",                       "PAC", "520"),
  e("Nepal",                       "ASI", "524"),
  e("Netherlands",                 "EUR", "528"),
  e("Nevis",                       "CAR", undefined, -62.61, 17.16),
  e("New Caledonia & Dependencies","PAC", "540"),
  e("Nueva Esparta",               "SAM", undefined, -63.97, 10.95),
  e("New Zealand",                 "PAC", "554"),
  e("New Zealand Antarctica",      "ANT", undefined, 170.00, -80.00),
  e("Nicaragua",                   "CAM", "558"),
  e("Niger",                       "AFR", "562"),
  e("Nigeria",                     "AFR", "566"),
  e("Niue",                        "PAC", undefined, -169.87, -19.05),
  e("Norfolk Island",              "PAC", undefined, 167.95, -29.04),
  e("Northern Marianas",           "PAC", undefined, 145.74, 15.21),
  e("North Macedonia",             "EUR", "807"),
  e("Norway",                      "EUR", "578"),
  e("Norwegian Dependencies",      "ANT", undefined, 3.00, -54.00),
  e("Ogasawara",                   "PAC", undefined, 142.16, 27.09),
  e("Oman",                        "ME",  "512"),
  // P
  e("Pakistan",                    "ASI", "586"),
  e("Palau, Republic of",          "PAC", "585"),
  e("Palestine",                   "ME",  "275"),
  e("Panama",                      "CAM", "591"),
  e("Papua (Irian Jaya)",          "ASI", undefined, 138.00, -4.00),
  e("Papua New Guinea",            "PAC", "598"),
  e("Paraguay",                    "SAM", "600"),
  e("Peru",                        "SAM", "604"),
  e("Philippines",                 "ASI", "608"),
  e("Pitcairn Island",             "PAC", undefined, -130.10, -25.07),
  e("Poland",                      "EUR", "616"),
  e("Portugal",                    "EUR", "620"),
  e("Prince Edward Island",        "NA",  undefined, -63.30, 46.42),
  e("Puerto Rico",                 "CAR", undefined, -66.59, 18.22),
  e("Qatar",                       "ME",  "634"),
  // R
  e("Ras Al Khaimah",              "ME",  undefined, 55.95, 25.79),
  e("Reunion",                     "IND", undefined, 55.54, -21.11),
  e("Rodrigues Island",            "IND", undefined, 63.43, -19.73),
  e("Romania",                     "EUR", "642"),
  e("Russia",                      "EUR", "643"),
  e("Russia in Asia (Siberia)",    "ASI", undefined, 105.00, 60.00),
  e("Rwanda",                      "AFR", "646"),
  e("Ryukyu Islands",              "PAC", undefined, 127.94, 26.51),
  // S
  e("Saba & Sint Eustatius",       "CAR", undefined, -63.23, 17.49),
  e("Sabah (North Borneo)",        "ASI", undefined, 116.00, 5.95),
  e("Saint-Barthélemy",            "CAR", undefined, -62.83, 17.90),
  e("Saint Helena",                "ATL", undefined, -5.72, -15.97),
  e("Saint Kitts",                 "CAR", undefined, -62.78, 17.34),
  e("Saint Lucia",                 "CAR", "662"),
  e("Saint-Martin (France)",       "CAR", undefined, -63.05, 18.08),
  e("Saint Pierre & Miquelon",     "NA",  undefined, -56.34, 46.78),
  e("Saint Vincent and Grenadines","CAR", "670"),
  e("Samoa",                       "PAC", "882"),
  e("Samoa, American",             "PAC", undefined, -170.13, -14.27),
  e("San Andres & Providencia",    "CAR", undefined, -81.71, 13.38),
  e("San Marino",                  "EUR", "674"),
  e("Sao Tome & Principe",         "AFR", "678"),
  e("Sarawak",                     "ASI", undefined, 113.99, 2.72),
  e("Sardinia",                    "EUR", undefined, 9.00, 40.00),
  e("Saudi Arabia",                "ME",  "682"),
  e("Scotland",                    "EUR", undefined, -3.18, 56.95),
  e("Senegal",                     "AFR", "686"),
  e("Serbia",                      "EUR", "688"),
  e("Seychelles",                  "IND", "690"),
  e("Sharjah",                     "ME",  undefined, 55.40, 25.36),
  e("Sicily",                      "EUR", undefined, 14.00, 37.50),
  e("Sierra Leone",                "AFR", "694"),
  e("Sikkim",                      "ASI", undefined, 88.51, 27.53),
  e("Singapore",                   "ASI", "702"),
  e("Sint Maarten (Netherlands)",  "CAR", undefined, -63.05, 18.04),
  e("Slovakia",                    "EUR", "703"),
  e("Slovenia",                    "EUR", "705"),
  e("Socotra",                     "IND", undefined, 53.92, 12.46),
  e("Solomon Islands",             "PAC", "090"),
  e("Somalia",                     "AFR", "706"),
  e("Somaliland",                  "AFR", undefined, 46.20, 9.55),
  e("South Africa",                "AFR", "710"),
  e("South Georgia & the South Sandwich Islands","ATL", undefined, -36.50, -54.50),
  e("South Ossetia",               "ASI", undefined, 44.00, 42.50),
  e("South Sudan",                 "AFR", "728"),
  e("Spain",                       "EUR", "724"),
  e("Spitsbergen",                 "EUR", undefined, 15.65, 78.22),
  e("Sri Lanka",                   "ASI", "144"),
  e("Srpska",                      "EUR", undefined, 17.76, 44.78),
  e("Sudan",                       "AFR", "729"),
  e("Sulawesi",                    "ASI", undefined, 121.00, -1.50),
  e("Sumatra",                     "ASI", undefined, 99.00, -0.50),
  e("Suriname",                    "SAM", "740"),
  e("Swaziland (Eswatini)",        "AFR", "748"),
  e("Sweden",                      "EUR", "752"),
  e("Switzerland",                 "EUR", "756"),
  e("Syria",                       "ME",  "760"),
  // T
  e("Taiwan, R.O.C.",              "ASI", "158"),
  e("Tajikistan",                  "ASI", "762"),
  e("Tanzania",                    "AFR", "834"),
  e("Tasmania",                    "PAC", undefined, 146.36, -41.45),
  e("Thailand",                    "ASI", "764"),
  e("Tibet",                       "ASI", undefined, 89.13, 31.00),
  e("Timor-Leste",                 "ASI", "626"),
  e("Togo",                        "AFR", "768"),
  e("Tokelau",                     "PAC", undefined, -171.85, -8.97),
  e("Tonga",                       "PAC", "776"),
  e("Transnistria",                "EUR", undefined, 29.48, 46.83),
  e("Trinidad & Tobago",           "CAR", "780"),
  e("Tristan da Cunha",            "ATL", undefined, -12.28, -37.10),
  e("Tunisia",                     "AFR", "788"),
  e("Turkey in Asia",              "ASI", "792"),
  e("Turkey in Europe",            "EUR", undefined, 28.97, 41.01),
  e("Turkmenistan",                "ASI", "795"),
  e("Turks & Caicos Islands",      "CAR", undefined, -71.80, 21.78),
  e("Tuvalu",                      "PAC", "798"),
  // U
  e("Uganda",                      "AFR", "800"),
  e("Ukraine",                     "EUR", "804"),
  e("Umm Al Qaiwain",              "ME",  undefined, 55.55, 25.57),
  e("United States (Contiguous)",  "NA",  "840"),
  e("Uruguay",                     "SAM", "858"),
  e("Uzbekistan",                  "ASI", "860"),
  // V
  e("Vanuatu",                     "PAC", "548"),
  e("Vatican City",                "EUR", undefined, 12.45, 41.90),
  e("Venezuela",                   "SAM", "862"),
  e("Vietnam",                     "ASI", "704"),
  e("Virgin Islands, British",     "CAR", undefined, -64.62, 18.42),
  e("Virgin Islands, U.S.",        "CAR", undefined, -64.81, 17.74),
  // W
  e("Wake Island",                 "PAC", undefined, 166.64, 19.30),
  e("Wales",                       "EUR", undefined, -3.18, 52.13),
  e("Wallis & Futuna Islands",     "PAC", undefined, -178.16, -14.30),
  e("Western Sahara",              "AFR", "732"),
  // Y
  e("Yemen",                       "ME",  "887"),
  // Z
  e("Zambia",                      "AFR", "894"),
  e("Zanzibar",                    "AFR", undefined, 39.20, -6.16),
  e("Zil Elwannyen Sesel",         "IND", undefined, 50.71, -9.40),
  e("Zimbabwe",                    "AFR", "716"),
];

// Quick-lookup maps
export const TCC_BY_NAME = new Map<string, TccEntry>(TCC_DATA.map(t => [t.name, t]));
export const TCC_BY_GEO_ID = new Map<string, TccEntry>(
  TCC_DATA.filter(t => t.geoId).map(t => [t.geoId!, t])
);
export const TCC_TOTAL = TCC_DATA.length;
export const TCC_MEMBERSHIP_THRESHOLD = 100;
